name: Delete Deployments

# Trigger the workflow on push to the feature branch (or other branches)
on:
  push:
    branches:
      - v23.8.stable  # Change this to the branch you want to trigger the workflow on

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Environment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages  # Change this to your environment variable if needed
          onlyRemoveDeployments: true
