name: Delete Deployments

# Trigger the workflow manually or on a specific event, such as `push` or `workflow_dispatch`
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to delete'
        required: false
        default: 'github-pages'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          onlyRemoveDeployments: true
