name: Delete Deployments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to delete'
        required: false
        default: 'github-pages'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:      
      - name: Delete Environment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          onlyRemoveDeployments: true
